Update conver

diff --git a/conver b/conver
--- a/conver
+++ b/conver
@@ -1,5 +1,230 @@
+Run set +e
+  set +e
+  test -f "envs/dev.tfvars" || { echo "ERROR: Missing tfvars file: envs/dev.tfvars"; exit 1; }
+  tofu plan -no-color -var-file="envs/dev.tfvars" -out=tfplan &> tofu_plan_stdout
+  tofu_plan_exit_code="$?"
+  cat tofu_plan_stdout
+  if [[ "$tofu_plan_exit_code" -ne 0 ]]; then
+      grep -i Error tofu_plan_stdout || true
+      echo "OpenTofu plan failed"
+      exit 1
+  fi
+      
+  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
+  env:
+    TF_IN_AUTOMATION: true
+    TF_INPUT: false
+    AWS_DEFAULT_REGION: us-east-1
+    AWS_REGION: us-east-1
+    AWS_ACCESS_KEY_ID: ***
+    AWS_SECRET_ACCESS_KEY: ***
+    AWS_SESSION_TOKEN: ***
+    TOFU_CLI_PATH: /home/runner/work/_temp/e99ef3e4-1c43-49f1-a323-cc36092c0e79
+module.aurora.data.aws_caller_identity.current: Reading...
+data.aws_iam_policy_document.aws_backup_assume_role: Reading...
+module.aurora.module.aurora_security_group.aws_security_group.this: Refreshing state... [id=sg-08b96e7fab8870702]
+module.aurora.module.rds_proxy_security_group[0].aws_security_group.this: Refreshing state... [id=sg-064a4f97c64e1d064]
+module.aurora.data.aws_region.current: Reading...
+module.aurora.data.aws_iam_policy_document.rds_proxy_assume[0]: Reading...
+module.aurora.aws_db_subnet_group.aurora: Refreshing state... [id=realtimeinsurance-dev-db-subnet-group]
+data.aws_iam_policy_document.aws_backup_assume_role: Read complete after 0s [id=2062047698]
+module.aurora.data.aws_region.current: Read complete after 0s [id=us-east-1]
+module.aurora.data.aws_iam_policy_document.rds_proxy_assume[0]: Read complete after 0s [id=2562693050]
+module.aurora.aws_iam_role.rds_proxy[0]: Refreshing state... [id=realtimeinsurance-dev-rds-proxy-role]
+module.aurora.data.aws_caller_identity.current: Read complete after 0s [id=058264370150]
+module.aurora.module.rds_proxy_security_group[0].aws_vpc_security_group_egress_rule.this["realtimeinsurance-dev-rds-proxy-sg-egress-0.0.0.0/0-all"]: Refreshing state... [id=sgr-0302a17b9b4dbc769]
+module.aurora.module.rds_proxy_security_group[0].aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-rds-proxy-sg-ingress-10.238.1.0/24-5432"]: Refreshing state... [id=sgr-0b40f97fb578db906]
+module.aurora.module.rds_proxy_security_group[0].aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-rds-proxy-sg-ingress-10.214.0.0/16-5432"]: Refreshing state... [id=sgr-0147460f8eba37d86]
+module.aurora.module.rds_proxy_security_group[0].aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-rds-proxy-sg-ingress-10.218.17.0/24-5432"]: Refreshing state... [id=sgr-0734d973ef7c14d96]
+module.aurora.module.rds_proxy_security_group[0].aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-rds-proxy-sg-ingress-10.235.1.0/24-5432"]: Refreshing state... [id=sgr-05b44551972516191]
+module.aurora.module.rds_proxy_security_group[0].aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-rds-proxy-sg-ingress-10.212.0.0/16-5432"]: Refreshing state... [id=sgr-098aaeb3dcfe71a30]
+module.aurora.module.rds_proxy_security_group[0].aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-rds-proxy-sg-ingress-10.215.0.0/16-5432"]: Refreshing state... [id=sgr-022df8c89e3fd1078]
+module.aurora.module.rds_proxy_security_group[0].aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-rds-proxy-sg-ingress-10.218.12.0/24-5432"]: Refreshing state... [id=sgr-055555eec412211a0]
+module.aurora.module.rds_proxy_security_group[0].aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-rds-proxy-sg-ingress-10.225.0.0/16-5432"]: Refreshing state... [id=sgr-0397763084fc3a783]
+module.aurora.module.rds_proxy_security_group[0].aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-rds-proxy-sg-ingress-10.236.1.0/24-5432"]: Refreshing state... [id=sgr-089f3eb8e19b2a045]
+module.aurora.module.rds_proxy_security_group[0].aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-rds-proxy-sg-ingress-10.217.3.0/24-5432"]: Refreshing state... [id=sgr-05f952976738300fd]
+module.aurora.module.aurora_security_group.aws_vpc_security_group_egress_rule.this["realtimeinsurance-dev-aurora-sg-egress-0.0.0.0/0-all"]: Refreshing state... [id=sgr-0e6b9aafc7c3b5a97]
+module.aurora.module.aurora_security_group.aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-aurora-sg-ingress-10.215.0.0/16-5432"]: Refreshing state... [id=sgr-076869e29d37bd8f4]
+module.aurora.module.aurora_security_group.aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-aurora-sg-ingress-10.217.3.0/24-5432"]: Refreshing state... [id=sgr-07ddbdd4ec277bc28]
+module.aurora.module.aurora_security_group.aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-aurora-sg-ingress-10.218.17.0/24-5432"]: Refreshing state... [id=sgr-054f3ae1f327c5b7c]
+module.aurora.module.aurora_security_group.aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-aurora-sg-ingress-10.225.0.0/16-5432"]: Refreshing state... [id=sgr-0ad33a0e922da0b66]
+module.aurora.module.aurora_security_group.aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-aurora-sg-ingress-10.235.1.0/24-5432"]: Refreshing state... [id=sgr-0c8e19d44d347ed91]
+module.aurora.module.aurora_security_group.aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-aurora-sg-ingress-10.238.1.0/24-5432"]: Refreshing state... [id=sgr-0d72aa32ac0ea0477]
+module.aurora.module.aurora_security_group.aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-aurora-sg-ingress-10.212.0.0/16-5432"]: Refreshing state... [id=sgr-02a43ab8e01d8defc]
+module.aurora.module.aurora_security_group.aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-aurora-sg-ingress-10.214.0.0/16-5432"]: Refreshing state... [id=sgr-012a1a482efe49940]
+module.aurora.module.aurora_security_group.aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-aurora-sg-ingress-10.236.1.0/24-5432"]: Refreshing state... [id=sgr-02b81759c70210181]
+module.aurora.module.aurora_security_group.aws_vpc_security_group_ingress_rule.this["realtimeinsurance-dev-aurora-sg-ingress-10.218.12.0/24-5432"]: Refreshing state... [id=sgr-0e664ecbd56fb4892]
+module.aurora.aws_rds_cluster.aurora: Refreshing state... [id=realtimeinsurance-dev-aurora-cluster]
+module.aurora.aws_vpc_security_group_ingress_rule.aurora_from_proxy[0]: Refreshing state... [id=sgr-0d5ba80ba2148b45c]
+module.aurora.aws_iam_role_policy.rds_proxy_secret_access[0]: Refreshing state... [id=realtimeinsurance-dev-rds-proxy-role:realtimeinsurance-dev-rds-proxy-secret-access]
+module.aurora.aws_db_proxy.aurora[0]: Refreshing state... [id=realtimeinsurance-dev-aurora-proxy]
+module.aurora.aws_rds_cluster_instance.writer: Refreshing state... [id=realtimeinsurance-dev-aurora-cluster-wr]
+module.aurora.aws_rds_cluster_instance.reader[0]: Refreshing state... [id=realtimeinsurance-dev-aurora-cluster-rd-1]
+module.aurora.aws_db_proxy_endpoint.aurora_reader[0]: Refreshing state... [id=realtimeinsurance-dev-aurora-proxy/realtimeinsurance-dev-aurora-proxy-reader]
+module.aurora.aws_db_proxy_default_target_group.aurora[0]: Refreshing state... [id=realtimeinsurance-dev-aurora-proxy]
+module.aurora.aws_db_proxy_target.aurora[0]: Refreshing state... [id=realtimeinsurance-dev-aurora-proxy/default/TRACKED_CLUSTER/realtimeinsurance-dev-aurora-cluster]
 
-cd "C:\Users\T012sp\Git repo\tf-aws-aurorapostgres-infra"
-git add -A
-git commit -m "Output RDS proxy application username"
-git push
+OpenTofu used the selected providers to generate the following execution
+plan. Resource actions are indicated with the following symbols:
+  + create
+  ~ update in-place
+-/+ destroy and then create replacement
+ <= read (data resources)
+
+OpenTofu will perform the following actions:
+
+  # module.aurora.data.aws_iam_policy_document.rds_proxy_secret_access[0] will be read during apply
+  # (config refers to values not yet known)
+ <= data "aws_iam_policy_document" "rds_proxy_secret_access" {
+      + id            = (known after apply)
+      + json          = (known after apply)
+      + minified_json = (known after apply)
+
+      + statement {
+          + actions   = [
+              + "secretsmanager:DescribeSecret",
+              + "secretsmanager:GetSecretValue",
+            ]
+          + effect    = "Allow"
+          + resources = [
+              + "arn:aws:secretsmanager:us-east-1:058264370150:secret:rds!cluster-de1d9261-65ef-4198-9ae6-73dcb0b25daf-rnMglh",
+              + (known after apply),
+            ]
+        }
+      + statement {
+          + actions   = [
+              + "rds-db:connect",
+            ]
+          + effect    = "Allow"
+          + resources = [
+              + "arn:aws:rds-db:us-east-1:058264370150:dbuser:cluster-FZCKYUP5O32DEWMAHJFEAXOG64/kfb_aurora_admin",
+              + "arn:aws:rds-db:us-east-1:058264370150:dbuser:cluster-FZCKYUP5O32DEWMAHJFEAXOG64/pgsi_ans04703015",
+            ]
+        }
+    }
+
+  # module.aurora.aws_db_proxy.aurora[0] will be updated in-place
+  ~ resource "aws_db_proxy" "aurora" {
+        id                             = "realtimeinsurance-dev-aurora-proxy"
+        name                           = "realtimeinsurance-dev-aurora-proxy"
+        tags                           = {
+            "Name" = "realtimeinsurance-dev-aurora-proxy"
+        }
+        # (14 unchanged attributes hidden)
+
+      - auth {
+          - auth_scheme               = "SECRETS" -> null
+          - client_password_auth_type = "POSTGRES_SCRAM_SHA_256" -> null
+          - iam_auth                  = "REQUIRED" -> null
+          - secret_arn                = "arn:aws:secretsmanager:us-east-1:058264370150:secret:rds!cluster-de1d9261-65ef-4198-9ae6-73dcb0b25daf-rnMglh" -> null
+        }
+      - auth {
+          - auth_scheme               = "SECRETS" -> null
+          - client_password_auth_type = "POSTGRES_SCRAM_SHA_256" -> null
+          - iam_auth                  = "REQUIRED" -> null
+          - secret_arn                = "arn:aws:secretsmanager:us-east-1:058264370150:secret:realtimeinsurance-NNrdwU" -> null
+        }
+      + auth {
+          + auth_scheme               = "SECRETS"
+          + client_password_auth_type = "POSTGRES_SCRAM_SHA_256"
+          + iam_auth                  = "REQUIRED"
+          + secret_arn                = "arn:aws:secretsmanager:us-east-1:058264370150:secret:rds!cluster-de1d9261-65ef-4198-9ae6-73dcb0b25daf-rnMglh"
+        }
+      + auth {
+          + auth_scheme               = "SECRETS"
+          + client_password_auth_type = (known after apply)
+          + iam_auth                  = "REQUIRED"
+          + secret_arn                = (known after apply)
+        }
+    }
+
+  # module.aurora.aws_iam_role_policy.rds_proxy_secret_access[0] will be updated in-place
+  ~ resource "aws_iam_role_policy" "rds_proxy_secret_access" {
+        id     = "realtimeinsurance-dev-rds-proxy-role:realtimeinsurance-dev-rds-proxy-secret-access"
+        name   = "realtimeinsurance-dev-rds-proxy-secret-access"
+      ~ policy = jsonencode(
+            {
+              - Statement = [
+                  - {
+                      - Action   = [
+        }
+      ~ tags_all                              = {
+          ~ "Name"                  = "realtimeinsurance-dev-aurora-cluster-rd-1" -> "realtimeinsurance-dev-aurora-cluster-reader-1"
+            # (8 unchanged elements hidden)
+        }
+      ~ writer                                = true -> (known after apply)
+        # (11 unchanged attributes hidden)
+    }
+
+  # module.aurora.aws_rds_cluster_instance.writer must be replaced
+-/+ resource "aws_rds_cluster_instance" "writer" {
+      + apply_immediately                     = (known after apply)
+      ~ arn                                   = "arn:aws:rds:us-east-1:058264370150:db:realtimeinsurance-dev-aurora-cluster-wr" -> (known after apply)
+      ~ availability_zone                     = "us-east-1b" -> (known after apply)
+      ~ ca_cert_identifier                    = "rds-ca-rsa2048-g1" -> (known after apply)
+      ~ db_parameter_group_name               = "default.aurora-postgresql17" -> (known after apply)
+      ~ db_subnet_group_name                  = "realtimeinsurance-dev-db-subnet-group" -> (known after apply)
+      ~ dbi_resource_id                       = "db-XTZ2EABSDCVRVXMB6SBH6PMREI" -> (known after apply)
+      ~ endpoint                              = "realtimeinsurance-dev-aurora-cluster-wr.cx08iswmk3mr.us-east-1.rds.amazonaws.com" -> (known after apply)
+      ~ engine_version_actual                 = "17.7" -> (known after apply)
+      ~ id                                    = "realtimeinsurance-dev-aurora-cluster-wr" -> (known after apply)
+      ~ identifier                            = "realtimeinsurance-dev-aurora-cluster-wr" -> "realtimeinsurance-dev-aurora-cluster-writer" # forces replacement
+      + identifier_prefix                     = (known after apply)
+      + kms_key_id                            = (known after apply)
+      + monitoring_role_arn                   = (known after apply)
+      ~ network_type                          = "IPV4" -> (known after apply)
+      ~ performance_insights_enabled          = true -> (known after apply)
+      ~ performance_insights_kms_key_id       = "arn:aws:kms:us-east-1:058264370150:key/8cd16281-724e-4ead-b9b3-f173a58dc123" -> (known after apply)
+      ~ performance_insights_retention_period = 465 -> (known after apply)
+      ~ port                                  = 5432 -> (known after apply)
+      ~ preferred_backup_window               = "08:59-09:29" -> (known after apply)
+      ~ preferred_maintenance_window          = "fri:07:02-fri:07:32" -> (known after apply)
+      ~ storage_encrypted                     = false -> (known after apply)
+        tags                                  = {
+            "Name" = "realtimeinsurance-dev-aurora-cluster-writer"
+        }
+      ~ writer                                = false -> (known after apply)
+        # (12 unchanged attributes hidden)
+    }
+
+  # module.aurora.aws_secretsmanager_secret.rds_proxy_application[0] will be created
+  + resource "aws_secretsmanager_secret" "rds_proxy_application" {
+      + arn                            = (known after apply)
+      + description                    = "RDS Proxy application user credentials for realtimeinsurance dev. Created empty by Terraform; value populated out-of-band."
+      + force_overwrite_replica_secret = false
+      + id                             = (known after apply)
+      + name                           = "realtimeinsurance-dev-rds-proxy-app-user"
+      + name_prefix                    = (known after apply)
+      + policy                         = (known after apply)
+      + recovery_window_in_days        = 30
+      + region                         = "us-east-1"
+      + tags                           = {
+          + "Name" = "realtimeinsurance-dev-rds-proxy-app-user"
+        }
+      + tags_all                       = {
+          + "Name"                  = "realtimeinsurance-dev-rds-proxy-app-user"
+          + "application_name"      = "realtimeinsurance"
+          + "business_ops_category" = "POL"
+          + "created_by"            = "PlatformEngineering@kyfb.com"
+          + "env_tier"              = "dev"
+          + "owned_by"              = "CloudOps@kyfb.com"
+          + "requested_by"          = "PMOGroup@kyfb.com"
+          + "source"                = "github.com/kfbmic/tf-aws-aurorapostgres-infra"
+          + "terraform"             = "true"
+        }
+    }
+
+Plan: 3 to add, 2 to change, 2 to destroy.
+
+Changes to Outputs:
+  + rds_proxy_application_username = "pgsi_ans04703015"
+
+Warning: Deprecated attribute
+
+  on ../../modules/aurora-postgres/rds_proxy.tf line 96, in data "aws_iam_policy_document" "rds_proxy_secret_access":
+  96:         "arn:aws:rds-db:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:dbuser:${aws_rds_cluster.aurora.cluster_resource_id}/${var.master_username}"
+
+The attribute "name" is deprecated. Refer to the provider documentation for
+details.
+
+(and 3 more similar warnings elsewhere)
